### ISSUE TITLE
Move GitHub account creation step of personal_website to after first website preview

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#1060]
Just had a call with @AppIns where we talked about how people going through the personal_website workshop felt the account creation step took too long.

**Comment by Bush1do** [comment]
So just clone the repo and shorten that part right?

**Comment by MaxWofford** [comment]
You'll have to change the order of the workshop by moving GitHub account creation to after the first website preview.

**Comment by Bush1do** [comment]
First website preview? Can you screenshot?

**Comment by paked** [comment]
Essentially, this (https://hackclub.com/workshops/personal_website/#part-i-setup) needs to be moved to to somewhere here (https://hackclub.com/workshops/personal_website/#part-iv-publishing).

The goal is to get people intro programming super quickly, instead of spending the first 30 minutes signing up to websites they've never heard of.

**Comment by Bush1do** [comment]
Seems easy enough, are the html files in the repo?

**Comment by MaxWofford** [comment]
It's a markdown file you can find right here https://github.com/hackclub/hackclub/blob/master/workshops/personal_website/README.md
