### ISSUE TITLE
Markcop won't catch errors

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#1069]

**Comment by MaxWofford** [comment]
Right now Markcop isn't running tests on all but the latest commit in https://github.com/hackclub/hackclub/pull/1065

**Comment by zachlatta** [comment]
Fixed by https://github.com/hackclub/hackclub/commit/714386ae6ce01d84749f0ab7c3b8921be2460667. Markcop is having trouble running running when files to check are manually passed as arguments.

For the time being, I'm removing parallelization and having it run on the entire repo (so not manually passing files to check).
