### ISSUE TITLE
Twilio Workshop: Explain how the Twilio library is included in the HTML code.

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#239]
In response to the question: "What is a problem you had with this workshop?" someone said "Understanding how Twilio was actually integrated into the app (as in, where it was defined)."

We should the following:

- What the Twilio library is
- Where it is "defined"
- How they can "define" it on their own website

**Comment by MaxWofford** [comment]
I agree with the problem stated in this issue, but after running the remote control workshop at @ZucchiniZe's high school, believe the problem is rooted in the way the workshop is formatted. Hackers are told to work in a provided environment (a pre-built jsbin) and are given no instructions on how to use twilio in a real website.

I think fixing this is more than just stating how to define the twilio library. We would need to revisit the use of our custom twilio library, the use of a pre-built jsbin, and our explanation of APIs given in the workshop.

**Comment by MaxWofford** [comment]
oops- didn't mean to press close!

**Comment by MaxWofford** [comment]
@jonleung Did you mean to title this issue `Remote Control Workshop: Explain how the Twilio library`?

**Comment by jonleung** [comment]
@MaxWofford I have renamed the issue.

**Comment by paked** [comment]
@MaxWofford I don't see the problem with adding a new section at the end of the workshop explaining how to integrate into a real site!

**Comment by jonleung** [comment]
This is fixed by #641
