### ISSUE TITLE
Create MVP guidelines on how to submit a workshop:

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#528]
- workshops should teach people to build something in ~1 hour
- workshops use text and gifs to communicate concepts
- workshops go in the workshops directory
- workshops are organized into playlists

**Comment by paked** [comment]
To quote the preliminary document that *somehow* made it into the repository.

> # Guidelines for Making a Workshop
>
>**_Note that this is only a preliminary draft of this document:_**
>
> - Go with something working over deriving something from scratch
> - Top down (i.e. ionic creator) vs to bottom up (learn the fundamentals of javascript or HTML)
> - Accessible to beginners to the topic and & people who are newer to the topic
> - Show how to do the thing as quickly as possible
>  - Explain them later
- Showing over prefacing
- Shorter over longer
- Smaller chunks over larger chunks
- Modular over linear
  - Reduce the amount of linear time
  - Explicitly communicate and design things so that people can jump around
  - Is shippable in ~30ish minutes (all subsequent chunks must be also shippable
    in 30 minutes or less as well)
- Explain only after showing
- Giving them something working over constructing something from scratch
- Choice over forced
  - Buffet styled, give them all of the code at the top
    - They can poke through the code
    - If they don't understand it there's an explanation underneath the phaser
      example
- Is relatable
- TODO
  - This guide needs to have examples of what is good vs what is not good

> ## Tools
> 
> - If you want to make gifs, we suggest using
  [LICEcap](http://www.cockos.com/licecap/). It may look dated, but it does an
  awesome job.
- When writing your workshop locally, use
  [grip](https://github.com/joeyespo/grip) to view the workshop exactly as it
  will render on GitHub!

**Comment by jonleung** [comment]
Perhaps include resources on how to add markdown

Individual
- Dropbox Paper

Collaborative
- BeeGit

Grip and your favorite editor

**Comment by zachlatta** [comment]
Why not keep it simple and encourage people to use Cloud9 (like how it's used in the workshops)? That's something everyone's already familiar with, it lets you edit in realtime with other people, and it's used in the workshops.

**Comment by MaxWofford** [comment]
@zachlatta Let's find a way to 80 char wrap in c9. That seems like the most tedious part of writing markdown for club leaders I've worked with.

**Comment by jonleung** [comment]
Hmm, the writing experience in C9 feels so jank to me...

**Comment by MaxWofford** [comment]
C9 also means they can run markserv.

**Comment by MaxWofford** [comment]
@jonleung Our clubs and workshops already use c9. It might be worth it to keep everything in one place.
