### ISSUE TITLE
Decide on how to standardize the use of Cloud9 and JS Bin

### ISSUE THREAD

**Issue by jonleung** [hackclub/hackclub#533]
The first thing to discuss for this task is to create a conversation with club leaders around

- which they are currently using
- which they think we should go with

**Comment by MaxWofford** [comment]
@jonleung Are we sure we want to support this? I remember @zachlatta mentioning we would use jsbin for the portfolio workshop and c9 for everything else.

**Comment by saescapa** [comment]
I like both JS Bin and C9, but I prefer C9 since it gives more of that feel of programming (not sure if it exists) but also, it's less confusing in my opinion. 

JS Bin is nice and easy too, but sometimes you go into problems when saving work, if you have a lot of copies of a file, it's hard to find others. 

Now, C9 is more advanced, and can be confusing, but I think it with good organization, it doesn't need to be. For example, having the auto save is nice, but honestly I don't think it's the greatest tool to have, it saves some time, but then you can run into issues, like the ones we had during hackCamp, instead of going with just plain Apache server (or any other). 

I lean towards C9 more, for me it's more secure and more reliable.

**Comment by JevinSidhu** [comment]
One thing I didn't enjoy about Codecademy is that its environment isn't the same as you would do your own development in. 

Cipher's been using C9 for all of our workshops. +1 to going for C9 solely.

**Comment by jonleung** [comment]
@saescapa @JevinSidhu, that's really helpful to know, thanks!

**Comment by paked** [comment]
How do we close this issue @jonleung?

**Comment by jonleung** [comment]
@paked we need to do a survey of who is using which tools. It seems that most people that I talk to have opted for using Cloud9.

Then we need to "Decide on how to standardize the use of Cloud9 and JS Bin". I just renamed this issue to reflect this.

**Comment by MaxWofford** [comment]
@jonleung Is this still the same issue? https://github.com/hackclub/hackclub/issues/533#event-488816259. it sounds like the new issue focuses on having everyone work on one platform but the original issue was for making our workshops compatible with both.

**Comment by zachlatta** [comment]
It seems like many people are using Cloud9 (I know @Bogidon is as well). I'm not sure how necessary it is to survey our existing leaders – it seems like we have enough information to make an educated decision.

I suggest the following:

- We use JS Bin for the first workshop and continue to use it for examples in our workshops
- We create an "onboarding" workshop designed to be run after the first workshop. It would:
  1. Get people on GitHub
  2. Set up everyone's Cloud9 environments (perhaps we have them all do development in a GitHub pages site?)
  3. Get everyone on Slack
  4. ???
  5. Profit
- All subsequent workshops use Cloud9 and link to the onboarding workshop at the beginning suggesting that the user goes through it if they haven't already

Thoughts?

**Comment by jonleung** [comment]
@zachlatta that sounds reasonable. I still want to do the survey first before going through with this.

**Comment by jonleung** [comment]
Conducting the survey now here in Slack:

https://starthackclub.slack.com/archives/random/p1449867053010744

**Comment by zachlatta** [comment]
Any updates from the survey?
