### ISSUE TITLE
Img Link in Maze Workshop

### ISSUE THREAD

**Issue by elishacoad** [hackclub/hackclub#707]
The Current img link in the "Maze" workshop opens (on some computers) a blank img. Zach Latta sent me this alternate link which fixes the problem. 
mazeImg = loadImage("https://surrogate.hackedu.us/i.imgur.com/7xDfW51.png");

**Comment by zachlatta** [comment]
Seems to be because the random Imgur proxy that was used in the workshop is
no longer online (cc @jonleung).

Easy fix: use our nifty Imgur proxy instead (as suggested by Elisha).

On Thu, Feb 11, 2016 at 9:40 PM, Elisha Coad <notifications@github.com>
wrote:

> The Current img link in the "Maze" workshop opens (on some computers) a
> blank img. Zach Latta sent me this alternate link which fixes the problem.
> mazeImg = loadImage("https://surrogate.hackedu.us/i.imgur.com/7xDfW51.png
> ");
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/707>.
>



-- 
Zach Latta
Hack Club | zach@hackclub.com

**Comment by MaxWofford** [comment]
@zachlatta @elishacoad What needs to be done to close this? Can we give it the `first-timers-only` tag?

**Comment by zachlatta** [comment]
The image link in Maze needs to be changed to use surrogate.

**Comment by zachlatta** [comment]
I'd bias against using `first-timers-only` simply because it's an easy and somewhat urgent change.
