### ISSUE TITLE
Cloud 9 requires credit cards

### ISSUE THREAD

**Issue by MaxWofford** [hackclub/hackclub#872]
This issue is to track spiking out a solution to the problem of hackers blocking on needing a credit card number when going through the personal_website workshop.

**Comment by zachlatta** [comment]
I'll email my contact at Cloud9 about this in a few days (they're probably flooded with emails about the acquisition right now).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Max WoffordSent: Saturday, July 16, 2016 12:13 PMTo: hackclub/hackclubReply To: hackclub/hackclubSubject: [hackclub/hackclub] Cloud 9 requires credit cards now (#872)This issue is to track spiking out a solution to the problem of hackers blocking on needing a credit card number when going through the personal_website workshop. 

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zachlatta** [comment]
I've gone ahead and emailed my contact at Cloud9, will modify the workshop as well.

**Comment by zachlatta** [comment]
Just submitted #873 to address this.
